<?php
    $errors = array_merge($signatureForm->getMessages(), $mailingListForm->getMessages());
    if ($errors) {
?>
<fieldset>
    <legend><?= $this->translate('Erreurs'); ?></legend>
    <div class="tab">
    <ul>
<?php
    foreach ($errors as $keyErrors) {
        foreach ($keyErrors as $message) {
            if ($message) {
?>
        <li class="red"><?= $message ?></li>
<?php
            }
        }
    }
?>
    </ul>
    </div>
</fieldset>
<?php   
    }
?>
