<article>
    <div class="item">
        <header>
            <h2><?= $title; ?></h2>
        </header>
        <div class="tab">
<?php
    // Display errors for signature form
    echo $this->partial(
        'petition/petition/formErrors.phtml',
        array(
            'form' => $signatureForm,
        )
    );

    // Display errors for mailing list form
    echo $this->partial(
        'petition/petition/formErrors.phtml',
        array(
            'form' => $mailingListForm,
        )
    );

    // Display signature form
    echo $this->partial(
        'petition/petition/formSignature.phtml',
        array(
            'form' => $signatureForm,
        )
    );

    // Display mailing list form
    echo $this->partial(
        'petition/petition/formMailingList.phtml',
        array(
            'form' => $mailingListForm,
        )
    );
            <p class="red">* <?= $this->translate("Champs obligatoires"); ?></p>
        </div>
    </div>
</article>