<a href="<?= $this->url('petition', ['pid' => $petition->id], [], true) ?>">
    <header>
        <h2><?= $petition->title; ?></h2>
        <ul class="inlined">
<?php
    if ($petition->latestStatus == 'WAITING E-SIGNATURES') {
?>
            <li><?= $this->translate('En attente de e-signatures') ?></li>
<?php
    }
    if ($petition->latestStatusDate) {
?>
            <li><?= sprintf($this->translate('Le %s'), $petition->latestStatusDate) ?></li>
<?php
    }
?>
        </ul>
    </header>
</a>
