<?php
    $this->headTitle($poll->content);
?>
<header class="hiddable">
	<h1><?= $this->translate('Votez pour la prochaine pétition.'); ?></h1>
	<p><?= $this->translate('Sur cette page, vous pouvez faire entendre votre voix! Choisissez quel sujet devrait aborder la prochaine pétition.'); ?></p>
	<p><?= $this->translate('Si aucun de ces sujets ne vous inspire, vous pouvez toujours nous en soumettre de nouveaux. Après étude du sujet et de sa faisabilité, nous l\'ajouterons au système de vote.'); ?></p>
</header>
<section>
<?php
    echo $this->partial(
        'poll/poll/poll.phtml',
        array(
            'poll' => $poll,
            'displayIfEmpty' => $displayIfEmpty,
        )
    );
?>
</section>
