<div class="item">
    <a href="<?= $this->url('vote', ['pid' => $answer->pid, 'aid' => $answer->id, 'action' => 'vote'], [], true) ?>">
        <header>
            <h2><?= $answer->content; ?></h2>
            <ul class="inlined">
                <li><?= sprintf($this->translate('Ajouté le %s'), $answer->creationDate); ?></li>
                <li><?= sprintf($this->translate('Proposé par %s'), $answer->author); ?></li>
            </ul>
        </header>
    </a>
    <div class="tab">
        <progress max="<?= $totalVoteCount; ?>" value="<?= $answer->voteCount; ?>"></progress>
        <span class="count"><?= sprintf($this->translate('%s votes'), $answer->voteCount ? $answer->voteCount : 0); /* TODO : format */ ?></span>
    </div>
</div>
