<?php

$title = sprintf($this->translate('Delete answer for "%s"'), $question->title);
$url   = $this->url('answer', [
	'action' => 'delete',
	'qid' => $question->id,
	'id' => $answer->id
], [], true);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    <?= sprintf($this->translate('Are you sure that you want to delete "%s" ?'), $this->escapeHtml($answer->title)); ?>
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="qid" value="<?= (int) $question->id ?>" />
    <input type="hidden" name="id" value="<?= (int) $answer->id ?>" />
    <button type="submit" class="btn btn-danger" name="del" value="yes"><?= $this->translate('Yes') ?></button>
    <button type="submit" class="btn btn-success" name="del" value="no"><?= $this->translate('No') ?></button>
</div>
</form>