<?php

$title = sprintf($this->translate('Edit answer for "%s"'), $question->title);
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$formTitle = $form->get('title');
$formTitle->setAttribute('class', 'form-control');
$formTitle->setAttribute('placeholder', 'Answer title');

$formId = $form->get('id');
$formId->setValue($answer->id);

$formQid = $form->get('qid');
$formQid->setValue($question->id);

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action',
    $this->url('answer', [
        'action' => 'edit',
        'qid'    => $question->id,
        'id'     => $answer->id,
    ], [], true)
);
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($formTitle) ?>
    <?= $this->formElement($formTitle) ?>
    <?= $this->formElementErrors()->render($formTitle, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($formId);
echo $this->formHidden($formQid);
echo $this->form()->closeTag();