<?php

$title = sprintf($this->translate('Answers to "%s"'), $question->title);
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?= $this->url('answer', ['action'=>'add'], [], true) ?>"><?= $this->translate('Add new answer'); ?></a>
</p>

<table class="table">
<tr>
    <th><?php echo $this->translate('Title'); ?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($answers as $answer) : ?>
<tr>
    <td><?= $this->escapeHtml($answer->title) ?></td>
    <td>
        <a href="<?= $this->url('answer', ['action'=>'edit', 'id' => $answer->id], [], true) ?>"><?= $this->translate('Edit'); ?></a>
        <a href="<?= $this->url('answer', ['action'=>'delete', 'id' => $answer->id], [], true) ?>"><?= $this->translate('Delete'); ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>