<?php $this->headTitle('Erreur 404');?>
<section>
    <article>
        <header>
            <h1><?= $this->translate('Erreur 404 : Page introuvable'); ?></h1>
        </header>
        <div class="item">

<?php if (isset($this->reason) && $this->reason): ?>

<?php
$reasonMessage= '';
switch ($this->reason) {
    case 'error-controller-cannot-dispatch':
        $reasonMessage = $this->translate('Le controlleur demandé n\'a pas pu traité la requête.');
        break;
    case 'error-controller-not-found':
        $reasonMessage = $this->translate('Le controlleur demandé n\'a pas pu être associé à une classe de controlleur existant.');
        break;
    case 'error-controller-invalid':
        $reasonMessage = $this->translate('Le controlleur demandé n\'est pas traitable.');
        break;
    case 'error-router-no-match':
        $reasonMessage = $this->translate('L\'URL demandée n\'a pas pu être associée à une route.');
        break;
    default:
        $reasonMessage = $this->translate('Nous n\'avons pas pu déterminer pour une erreur 404 est survenue.');
        break;
}
?>
            <header>
                <h2><?= $this->message; ?></h2>
                <ul class="inlined">
                    <li><?= $reasonMessage ?></li>
                </ul>
            </header>
            <div class="tab">
<?php endif ?>


<?php if (isset($this->controller) && $this->controller): ?>

<dl>
    <dt><?= $this->translate('Controlleur:'); ?></dt>
    <dd><?= $this->escapeHtml($this->controller) ?>
<?php
if (isset($this->controller_class)
    && $this->controller_class
    && $this->controller_class != $this->controller
) {
    echo '(' . sprintf($this->translate('résolu en %s'), $this->escapeHtml($this->controller_class)) . ')';
}
?>
</dd>
</dl>

<?php endif ?>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

<?php if(isset($this->exception) && ($this->exception instanceof Exception || $this->exception instanceof Error)): ?>
<hr/>
<h2><?= $this->translate('Informations additionnelles:'); ?></h2>
<h3><?= get_class($this->exception) ?></h3>
<dl>
    <dt><?= $this->translate('Fichier:'); ?></dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
    </dd>
    <dt><?= $this->translate('Message:'); ?></dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->exception->getMessage() ?></pre>
    </dd>
    <dt><?= $this->translate('Stack trace:'); ?></dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->exception->getTraceAsString() ?></pre>
    </dd>
</dl>
<?php
    $e = $this->exception->getPrevious();
    $icount = 0;
    if ($e) :
?>
<hr/>
<h2><?= $this->translate('Exceptions précédentes:'); ?></h2>
<ul class="unstyled">
    <?php while($e) : ?>
    <li>
        <h3><?= get_class($e) ?></h3>
        <dl>
            <dt><?= $this->translate('Fichier:'); ?></dt>
            <dd>
                <pre class="prettyprint linenums"><?= $e->getFile() ?>:<?= $e->getLine() ?></pre>
            </dd>
            <dt><?= $this->translate('Message:'); ?></dt>
            <dd>
                <pre class="prettyprint linenums"><?= $e->getMessage() ?></pre>
            </dd>
            <dt><?= $this->translate('Stack trace:'); ?></dt>
            <dd>
                <pre class="prettyprint linenums"><?= $e->getTraceAsString() ?></pre>
            </dd>
        </dl>
    </li>
    <?php
        $e = $e->getPrevious();
        $icount += 1;
        if ($icount >=50) {
            echo $this->translate("<li>Il se peut qu'il y ai plus d'exceptions, mais la mémoire du processus est limitée.</li>");
            break;
        }
        endwhile;
    ?>
</ul>
<?php endif; ?>

<?php else: ?>

<h3><?= $this->translate('Aucune exception disponible.'); ?></h3>

<?php endif ?>

<?php endif ?>
            </div>
        </div>
    </article>
</section>
