<?php $this->headTitle('Erreur');?>
<h1><?= $this->translate('Une erreur est survenue'); ?></h1>
<h2><?= $this->message ?></h2>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

<?php if(isset($this->exception) && ($this->exception instanceof Exception || $this->exception instanceof Error)): ?>
<hr/>
<h2><?= $this->translate('Informations additionnelles:'); ?></h2>
<h3><?= get_class($this->exception) ?></h3>
<dl>
    <dt><?= $this->translate('Fichier:'); ?></dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
    </dd>
    <dt><?= $this->translate('Message:'); ?></dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
    </dd>
    <dt><?= $this->translate('Stack trace:'); ?></dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
    </dd>
</dl>
<?php
    $e = $this->exception->getPrevious();
    $icount = 0;
    if ($e) :
?>
<hr/>
<h2><?= $this->translate('Exceptions précédentes:'); ?></h2>
<ul class="unstyled">
    <?php while($e) : ?>
    <li>
        <h3><?= get_class($e) ?></h3>
        <dl>
            <dt><?= $this->translate('Fichier:'); ?></dt>
            <dd>
                <pre class="prettyprint linenums"><?= $e->getFile() ?>:<?= $e->getLine() ?></pre>
            </dd>
            <dt><?= $this->translate('Message:'); ?></dt>
            <dd>
                <pre class="prettyprint linenums"><?= $this->escapeHtml($e->getMessage()) ?></pre>
            </dd>
            <dt><?= $this->translate('Stack trace:'); ?></dt>
            <dd>
                <pre class="prettyprint linenums"><?= $this->escapeHtml($e->getTraceAsString()) ?></pre>
            </dd>
        </dl>
    </li>
    <?php
        $e = $e->getPrevious();
        $icount += 1;
        if ($icount >= 50) {
            echo $this->translate("<li>Il se peut qu'il y ai plus d'exceptions, mais la mémoire du processus est limitée.</li>");
            break;
        }
        endwhile;
    ?>
</ul>
<?php endif; ?>

<?php else: ?>

<h3><?= $this->translate('Aucune exception disponible.'); ?></h3>

<?php endif ?>

<?php endif ?>
