<header class="hiddable">
    <h1>Bienvenu sur Agora pétitions!</h1>
    <p>Ce site propose des pétitions de haute qualité la ou tous les autres proposent des pétitions en quantité.</p>
    <p>Tous les deux mois, une nouvelle pétition sur le sujet de votre choix est publiée. Grâce à l'expertise d'avocats, la qualité et la faisabilité de nos pétitions sont assurées.</p>
    <!--
    <p>Si la pétition vous interèsse, il vous suffit de la signer éléctroniquement. Une fois les 500 000 e-signatures atteintes, vous recevrez chez vous la pétition au format papier ainsi qu'une enveloppe pré-affranchie. Il ne vous reste plus qu'à la signer et la mettre dans une boite à lettres.</p>
    <p>Pour chaque pétition, nous vous tiendrons informé des évolutions. En revanche, nous refusons de "spammer". Aussi vous recevrez uniquement des informations sur les pétitions que vous avez choisies.</p>
    -->
</header>
<section>
<?php
    if ($latestPetition) {
?>
        <article>
            <header>
                <h1>Dernière pétition publiée</h1>
            </header>
<?php
            echo $this->partial(
                'petition/petitions/petition.phtml', 
                array('petition' => $latestPetition)
            );
?>
        </article>
<?php
    }
?>

<?php
    echo $this->partial(
        'poll/poll/poll.phtml',
        array(
            'poll' => $latestPoll
        )
    );
?>

<?php
    if (count($oldPetitions)) {
?>
        <article>
            <header>
                <h1>Liste des dernière pétitions</h1>
            </header>
<?php
            foreach ($oldPetitions as $petition) {
                echo $this->partial(
                    'petition/petitions/petition.phtml', 
                    array(
                        'petition'         => $petition,
                    )
                );
            }
?>
        </article>
<?php
    }
?>
</section>
