<?php $this->headTitle('Accueil');?>
<header class="hiddable">
    <h1><?= $this->translate('Bienvenu sur Agora pétitions!'); ?></h1>
    <p><?= $this->translate('Ce site propose des pétitions de haute qualité la ou tous les autres proposent des pétitions en quantité.'); ?></p>
    <p><?= $this->translate('Tous les deux mois, une nouvelle pétition sur le sujet de votre choix est publiée. Grâce à l\'expertise d\'avocats, la qualité et la faisabilité de nos pétitions sont assurées.'); ?></p>
</header>
<section>
<?php
    if ($latestPetition) {
?>
        <article>
            <header>
                <h1><?= $this->translate('Dernière pétition publiée'); ?></h1>
            </header>
<?php
            echo $this->partial(
                'petition/petitions/petition.phtml', 
                array('petition' => $latestPetition)
            );
?>
        </article>
<?php
    }
?>

<?php
    echo $this->partial(
        'poll/poll/poll.phtml',
        array(
            'poll' => $latestPoll
        )
    );
?>

<?php
    if (count($oldPetitions)) {
?>
        <article>
            <header>
                <h1><?= $this->translate('Liste des dernière pétitions'); ?></h1>
            </header>
<?php
            foreach ($oldPetitions as $petition) {
                echo $this->partial(
                    'petition/petitions/petition.phtml', 
                    array(
                        'petition'         => $petition,
                    )
                );
            }
?>
        </article>
<?php
    }
?>
</section>
