<?php

$title = sprintf($this->translate('Answers for "%s"'), $question->title);
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($question->title); ?></h1>
<p>
    <a href="<?= $this->url('question', ['action'=> null, 'id' => null], [], true) ?>"><?= $this->translate('Return to question list'); ?></a>
</p>

<?php if (count($answers)) { ?>
<table class="table">
<tr>
    <th><?php echo $this->translate('Answer title'); ?></th>
</tr>
<?php foreach ($answers as $answer) { ?>
<tr>
    <td><?= $this->escapeHtml($answer->title) ?></td>
</tr>
<?php } ?>
</table>

<?php } else { ?>
<p>
	<?= $this->translate('No answer found for this question'); ?>
</p>

<?php } ?>