<?php

$title = $this->translate('Delete question');
$url   = $this->url('question', ['action' => 'delete', 'id' => $id], [], true);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    <?= sprintf($this->translate('Are you sure that you want to delete "%s" ?'), $this->escapeHtml($question->title)); ?>
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $question->id ?>" />
    <button type="submit" class="btn btn-danger" name="del" value="yes"><?= $this->translate('Yes') ?></button>
    <button type="submit" class="btn btn-success" name="del" value="no"><?= $this->translate('No') ?></button>
</div>
</form>