<?php

$title = $this->translate('My questions');
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?= $this->url('question', ['action'=>'add'], [], true) ?>"><?= $this->translate('Add new question'); ?></a>
</p>

<table class="table">
<tr>
    <th><?php echo $this->translate('Title'); ?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($questions as $question) : ?>
<tr>
    <td><?= $this->escapeHtml($question->title) ?></td>
    <td>
        <a href="<?= $this->url('question', ['action'=>'answer', 'id' => $question->id], [], true) ?>"><?= $this->translate('Answer'); ?></a>
        <a href="<?= $this->url('question', ['action'=>'edit', 'id' => $question->id], [], true) ?>"><?= $this->translate('Edit'); ?></a>
        <a href="<?= $this->url('question', ['action'=>'delete', 'id' => $question->id], [], true) ?>"><?= $this->translate('Delete'); ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>