<?= $this->doctype() ?>

<html>
    <head>
        <!-- Title -->
        <?=
            $this->headTitle($this->translate('Agora Petition'))
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ?>
        <!-- Meta -->
        <?=
            $this->headMeta()
                ->setCharset('utf-8')
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Styles -->
        <?=
            $this->headLink([
                'rel'  => 'shortcut icon',
                'type' => 'image/x-icon',
                'href' => $this->basePath('img/favicon.ico'),
            ])
                ->prependStylesheet($this->basePath('css/main.css'))
                ->prependStylesheet($this->basePath('css/ie9.css'), 'screen', 'IE9')
                ->prependStylesheet($this->basePath('css/ie8.css'), 'screen', 'IE8')
        ?>
        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/main.min.js'))
            ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js')
        ?>
    </head>
    <body>
        <!-- Wrapper -->
        <div id="wrapper">
            <!-- Header -->
            <header id="header">
                <div class="inner">
                    <!-- Logo -->
                    <a href="<?= $this->url('home', [], [], true) ?>" class="logo">
                        <span class="symbol"><img src="img/logo.png" alt="" /></span>
                        <span class="title"><?= $this->translate('Agora Petition'); ?></span>
                    </a>
                    <!-- Menu logo -->
                    <nav>
                        <ul>
                            <li><a href="#menu"><?= $this->translate('Menu'); ?></a></li>
                        </ul>
                    </nav>
                </div>
            </header>
            <!-- Menu -->
            <nav id="menu">
                <h2><?= $this->translate('Menu'); ?></h2>
                <ul>
                    <li><a href="<?= $this->url('home', [], [], true) ?>"><?= $this->translate('Home'); ?></a></li>
                    <li><a href="<?= $this->url('question', [], [], true) ?>"><?= $this->translate('Current vote'); ?></a></li>
                    <li><a href="<?= $this->url('question', [], [], true) ?>"><?= $this->translate('Previous petitions'); ?></a></li>
                    <li><a href="<?= $this->url('question', [], [], true) ?>"><?= $this->translate('About us'); ?></a></li>
                </ul>
            </nav>
            <!-- Main content -->
            <div id="content">
                <div class="inner">
                    <?= $this->content; ?>
                </div>
            </div>
        </div>
        <!-- Footer -->
        <footer id="footer">
            <div class="inner">
                <ul class="copyright">
                    <li><?= sprintf($this->translate('&copy; %s by Agora Petition Association. All rights reserved.'), date('Y')); ?></li>
                    <li><?= $this->translate('Design: '); ?><a href="http://html5up.net">HTML5 UP</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>