<header class="hiddable">
    <h1>Consultez les pétitions publiées.</h1>
    <p>Ici, vous trouverez toutes les pétitions que nous avons écrites depuis notre création.</p>
    <p>Vous pouvez toujours suivre et/ou signer une ancienne pétition. Votre signature peut faire la différence!</p>
    <p>Dans le cas ou une pétition a atteint les 500 000 signatures papiers, vous ne pourrez plus la signer. En revanche vous pouvez toujours vous inscrire à la newsletter de celle-ci afin de rester informé de son évolution.</p>
</header>
<section>
<?php
    echo $this->partial(
        'petition/petitions/petitions.phtml',
        array(
            'petitions' => $petitions
        )
    );
?>
</section>
