<?php $this->headTitle('Liste des pétitions');?>
<header class="hiddable">
    <h1><?= $this->translate('Consultez les pétitions publiées.'); ?></h1>
    <p><?= $this->translate('Ici, vous trouverez toutes les pétitions que nous avons écrites depuis notre création.'); ?></p>
    <p><?= $this->translate('Vous pouvez toujours suivre et/ou signer une ancienne pétition. Votre signature peut faire la différence!'); ?></p>
    <p><?= $this->translate('Dans le cas ou une pétition a atteint les 500 000 signatures papiers, vous ne pourrez plus la signer. En revanche vous pouvez toujours vous inscrire à la newsletter de celle-ci afin de rester informé de son évolution.'); ?></p>
</header>
<section>
<?php
    echo $this->partial(
        'petition/petitions/petitions.phtml',
        array(
            'petitions' => $petitions
        )
    );
?>
</section>
