<div class="item">
    <a href="<?= $this->url('petition', ['pid' => $petition->id], [], true) ?>">
        <header>
            <h2><?= $petition->title; ?></h2>
            <ul class="inlined">
                <?php if ($petition->latestStatus) {?>
                <li><?= $petition->latestStatus; ?></li>
                <?php } ?>
                <?php if ($petition->latestStatusDate) {?>
                <li><?= sprintf($this->translate('Le %s'), $petition->latestStatusDate); ?></li>
                <?php } ?>
            </ul>
        </header>
    </a>
    <div class="tab">
        <?php
            if ($petition->latestStatus == 'En attente d\'e-signatures') {
        ?>
            <progress max="500000" value="<?= $petition->signatureCount; ?>"></progress>
            <span class="count"><?= sprintf($this->translate('%s e-signatures'), $petition->signatureCount ? $petition->signatureCount : 0); /* TODO : format */ ?></span>
        <?php
            } else {
            // TODO
            }
        ?>
    </div>
</div>
