<div class="item">
    <a href="<?= $this->url('petition', ['pid' => $petition->id], [], true) ?>">
        <header>
            <h2><?= $petition->title; ?></h2>
            <ul class="inlined">
                <li><?= $petition->latestStatus; ?></li>
                <li><?= $petition->latestStatusDate; ?></li>
            </ul>
        </header>
    </a>
    <div class="tab">
        <?php
            if ($petition->latestStatus == 'En attente d\'e-signatures') {
        ?>
            <progress max="500000" value="<?= $petition->signatureCount; ?>"></progress>
            <span class="count"><?= $petition->signatureCount ? $petition->signatureCount : 0; /* TODO : format */ ?> e-signatures</span>
        <?php
            } else {
            // TODO
            }
        ?>
    </div>
</div>
