<?php
    // Should we display anything?
    if (count($petitions) !== 0 || $displayIfEmpty === true) {
?>
<article>
    <header>
        <h1><?= $title ?></h1>
    </header>
<?php
        if (count($petitions) === 0) {
?>
    <p><?= $this->translate("Il n'y a pas de pétition actuellement disponible. Revenez plus tard!"); ?></p>
<?php
        } else {
            // Display each petition as an item
            foreach ($petitions as $petition) {
                echo $this->partial(
                    'petition/petition/item.phtml',
                    array(
                        'petition' => $petition,
                    )
                );
            }
        }
?>
</article>
<?php
    }
?>